name: Nginx CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: dhparam 
      id: dhparam-generate
      # run: openssl dhparam -out dhparam-2048.pem 2048
      run: |
        openssl dhparam -out dhparam-2048.pem 2048
      
